version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=quiz_dba
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=quiz
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redisdata:/data
  app:
    build: ./src/QuizApp
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: quiz_dba
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: quiz
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '8080:80'
    depends_on:
      - postgres
      - redis